spring :
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/techtalk?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234

  # jpa
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        default_batch_fetch_size: 100
    hibernate:
      ddl-auto: create
    show-sql: true

  # redis
  data :
    redis:
      host: localhost
      port: 6379
